### ISSUE TITLE
Create GitHub Repository and Set Up Environment

### ISSUE THREAD

**Issue by Amir-Hussein-OTH** [Amir-Hussein-OTH/made-template#1]
**Task:** Create a public GitHub repository for the module.
  - [x] Fork the [made-template repository](https://github.com/jvalue/made-template).
  - [x] Customize the repository to align with the module's requirements.

-**Submission:**
  - [x] Answer the [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdWBL0pqio0lvwstpY5ipn71bGwfXg26KVlMG6AwK5qxVBDDw/viewform?usp=sf_link) with the link to your GitHub repository.

 **Optional:**
  - [x] If applicable, set up the Python / Jayvee / Jupyter Notebook environment.

**Comment by Amir-Hussein-OTH** [comment]
Done
