### ISSUE TITLE
Submit Project Plan and Get Familiar with Jayvee Basics

### ISSUE THREAD

**Issue by Amir-Hussein-OTH** [Amir-Hussein-OTH/made-template#2]
## Task Description:

 **Submit Project Plan:**
   - [x] Create a Markdown file named `project-plan.md`.
   - [x] Place it in the `/project` directory of your repository.
   - [x] Follow the provided example to structure your project plan.

 **Watch Jayvee Basics:**
   - [x] [Core Concepts video](https://www.youtube.com/watch?v=X8fOK8JIBZA)
   - [x] [Core Concepts documentation](https://jvalue.github.io/jayvee/docs/user/core-concepts)
   - [x] [Tutorial examples](https://jvalue.github.io/jayvee/docs/category/jayvee-examples)

**Submission:**
- [x] Ensure the project plan (`project-plan.md`) is submitted to the `/project` directory.

**Comment by Amir-Hussein-OTH** [comment]
done
