### ISSUE TITLE
Build Automated Data Pipeline

### ISSUE THREAD

**Issue by Amir-Hussein-OTH** [Amir-Hussein-OTH/made-template#3]
## Task Description:

**Follow Project Plan:**
   - [x] Refer to your project plan to guide the development of an automated data pipeline.

 **Write Data Pipeline Script:**
   - [x] Write a script in Python or Jayvee (as per your preference).
   

  **The script should:**

      - [x]  Pull the chosen datasets from the internet.
      - [x] Transform and fix errors in the data.
      - [x]  Store the processed data in the `/data`

**Comment by Amir-Hussein-OTH** [comment]
done
