### ISSUE TITLE
Automated Data Pipeline Execution

### ISSUE THREAD

**Issue by Amir-Hussein-OTH** [Amir-Hussein-OTH/made-template#4]
### Tasks:
- [x] Add automated tests for the project.
- [x] Create a /project/tests.sh file for executing tests.
- [x] Include at least one test case on the system-test level.
- [x] Execute the data pipeline in the tests.
- [x] Validate the existence of output file(s).
- [x] Update issues as necessary.

**Comment by Amir-Hussein-OTH** [comment]
I went through this task and successfully finished it
